### PR TITLE
All your base tests fix

### PR DESCRIPTION
**Pull request by Nerwosolek**
I have changed two tests: test_single_zero, test_multiple_zeros.
They have expected 0 length result array but as input and output bases are correct these are just proper representations of zero number.
So the results should be zeros, which in both cases are arrays of length 1 with zero digit.

### CODE REVIEW

**Review by wolf99 — DISMISSED** [review]
LGTM, thanks!

**Comment by Nerwosolek** [comment]
As soon as I am not on mobile too :)

**Comment by Nerwosolek** [comment]
OK. So it looks like there are reference solutions which are tested with updated tests and they are failing. Which is good bc now expected value is 1 instead of 0.

**Comment by Nerwosolek** [comment]
I can update the example solution tommorrow.

**Review by wolf99 — CHANGES_REQUESTED** [review]

**Review by wolf99 — APPROVED** [review]

**Comment by wolf99** [comment]
LGTM

**Pull request merged**
