### PR TITLE
Correct workflow names

### LINKED ISSUE #629: CI: split tests from checks and add clang build
It would be good to have the exercise tests built on their own job, separate job to the "checks" (`verify-indent`, `check-unitybegin`, `verify -unity-version`, `shellcheck`).

It would also be good, once the above is in place, to build the tests with Clang (also on its own job) as well as with GCC, as used to happen when Travis CI was used.
It seems the Ubuntu 18.04 GH job runner virtual environment that we use has both Clang and GCC available (https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) and actually I'm not too sure which is being used currently - I assumed `$CC` picked up GCC automagically but am not really sure!

Thoughts?

### PR DESCRIPTION
**Pull request by wolf99**
Hopefully, fixes #629

### CODE REVIEW

**Comment by wolf99** [comment]
Nope, still not running the `build.yaml` for some reason - any ideas?

**Comment by wolf99** [comment]
Thats done it! 🕺

**Comment by ryanplusplus** [comment]
Thanks! Any idea why the original change didn't fail CI?

**Review by ryanplusplus — APPROVED** [review]

**Comment by wolf99** [comment]
Seems like if the job configs themselves are wrong they just don't run. Without running it couldn't fail.

**Pull request merged**
