### PR TITLE
Launch the C track

### LINKED ISSUE #8: Launch planning
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

If you are interested in leading the charge on getting this track launched, then comment below, and I'll help get this party started based on whatever is current at the time.

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

### PR DESCRIPTION
**Pull request by ryanplusplus**
Closes #8

### CODE REVIEW

**Comment by wolf99** [comment]
FYI, we could prossibly remove the "hacktoberfest" section from the README.md as part of this PR because:
1. It references the work to move the track to ready.
2. October is over.

**Comment by ryanplusplus** [comment]
@wolf99 good call, done.

**Comment by wolf99** [comment]
This is good to merge if you think #5  is covered (or at an acceptable level) I guess?

**Comment by ryanplusplus** [comment]
Yeah, let's go ahead and do this. #228 is nice to have and will be done soon.

**Pull request merged**
