### PR TITLE
Replace usage of UnityBegin/UnityEnd with UNITY_BEGIN/UNITY_END

### PR DESCRIPTION
**Pull request by ahans**
See discussion [here](https://github.com/exercism/c/pull/943#pullrequestreview-1847355007)

Done via:
```
for f in $(find . -name "test_*.c"); do
    sed -i -e 's/UnityBegin\(.*\);/UNITY_BEGIN();/' $f
    sed -i -e 's/UnityEnd/UNITY_END/' $f
done
```

### CODE REVIEW

**Review by ryanplusplus — APPROVED** [review]
Thanks!

**Comment by siebenschlaefer** [comment]
I know it's too late now, but for future changes like this please add `[no important files changed]` to the commit message of the merge. Otherwise thousands of solutions get re-compiled and re-tested which can take a long time and be expensive.
see https://exercism.org/docs/building/tracks#h-avoiding-triggering-unnecessary-test-runs

**Comment by ahans** [comment]
> I know it's too late now, but for future changes like this please add `[no important files changed]` to the commit message of the merge. Otherwise thousands of solutions get re-compiled and re-tested which can take a long time and be expensive. see https://exercism.org/docs/building/tracks#h-avoiding-triggering-unnecessary-test-runs

Oh, I had no idea! Sorry about this!

Would it be a good idea to provide a PR template that contains a reminder about this, as in

> - [ ] `[no important files changed] has been added to commits that don't affect tests

@ryanplusplus, what do you think?

**Comment by ryanplusplus** [comment]
@ahans There's supposed to be an automated comment from an exercism bot to notify/remind about this. I'm not sure why it didn't fire for your PR, though...

**Comment by ryanplusplus** [comment]
> @ahans There's supposed to be an automated comment from an exercism bot to notify/remind about this. I'm not sure why it didn't fire for your PR, though...

See https://github.com/exercism/c/pull/949#issuecomment-1913800101 for an example.

**Comment by wolf99** [comment]
Could be good to update the track documentation for this as I think we may reference this somewhere there.

**Pull request merged**
