### PR TITLE
Update LEARNING.md

### PR DESCRIPTION
**Pull request by Prathu121**

### CODE REVIEW

**Comment by kotp** [comment]
In order to be registered as invalid in terms of Hacktoberfest, the label should be `invalid`.

**Comment by kotp** [comment]
At least, and that would be nice, I think, I am unaware if `hacktoberfest spam` works.  It would be nice if it does.

**Comment by ryanplusplus** [comment]
> In order to be registered as invalid in terms of Hacktoberfest, the label should be `invalid`.

Their docs say any label with invalid or spam in the name will work. This may be new for this year's Hacktoberfest.

**Comment by kotp** [comment]
I like the specific label myself, so that would be a nice way to do so.  I could think of situations where something could be invalid, to apply, that you would want to mark as such, but might be valuable in the learning, so not invalid for credit for Hacktoberfest.

**Pull request closed without merging**
