### PR TITLE
color tests

### PR DESCRIPTION
**Pull request by joshgoebel**
- enh: tests show results in color

Adds `-DUNITY_OUTPUT_COLOR` to all makefiles

### CODE REVIEW

**Comment by joshgoebel** [comment]
Test runner may need updates also?

**Review by wolf99 — APPROVED** [review]
LGTM

Test runner may need update, I can't recall. It's in its own c-test-runner repo.

**Review by ryanplusplus — APPROVED** [review]

**Comment by siebenschlaefer** [comment]
Are you sure that doesn't break the current test runner?

There's a (IMHO correct) solution in the queue where all tests pass but it's marked as "Failed".
I just tried one of my old exercises and get the same behavior: All tests pass but I can't submit because the test runner thinks "An error occurred".

**Comment by joshgoebel** [comment]
The test runner may need to be updated to use `sed` to remove the new define to get black and white.

**Pull request merged**
