### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by sudhackar**
A small PR that fixes some spelling.

qq: What's `typefdef` ? Is it actually spelled that way?

### CODE REVIEW

**Comment by ryanplusplus** [comment]
@wolf99 do you have any idea what's going on with the failed link check? The link that lychee is complaining about works for me and, given that it's a GitHub URL, I'm confused how a GitHub runner would have network connectivity issues that I'm not seeing.

**Comment by sudhackar** [comment]
@ryanplusplus I'm getting 403 with curl as well.
```bash
$ curl -v https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
..
< HTTP/2 403
< x-azure-ref: 0dp5VYgAAAADQ8juZsIkxRYm02sztLJJGQk9NMDJFREdFMDgxNwA1OTZkNzhhMi1jYTVmLTQ3OWQtYmNkYy0wODM1ODMzMTc0YjI=
< accept-ranges: bytes
< date: Tue, 12 Apr 2022 15:44:54 GMT
< via: 1.1 varnish
< x-served-by: cache-bom4741-BOM
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1649778295.701392,VS0,VE8
< strict-transport-security: max-age=31557600
<
* Connection #0 to host docs.github.com left intact
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>0dp5VYgAAAADQ8juZsIkxRYm02sztLJJGQk9NMDJFREdFMDgxNwA1OTZkNzhhMi1jYTVmLTQ3OWQtYmNkYy0wODM1ODMzMTc0YjI=</span></div></div></body></html>
```

**Comment by sudhackar** [comment]
I can add a new User-Agent as well in this PR for [lychee](https://github.com/lycheeverse/lychee)
```
    -u, --user-agent <user-agent>              User agent [default: lychee/0.9.0]
```
Default currently 403s
```bash
$ curl -v -H 'user-agent: lychee/0.9.0' https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
...
< HTTP/2 403
...
```

**Comment by ryanplusplus** [comment]
> A simple User-Agent fixes the problem

Great find!

> I can add a new User-Agent as well in this PR for [lychee](https://github.com/lycheeverse/lychee)

That would be awesome, but let's do it in a follow-up PR. I'll merge this as is since the failure is unrelated to the change.

**Pull request merged**
