### PR TITLE
void tearDown

### PR DESCRIPTION
**Pull request by babugyan**

### CODE REVIEW

**Comment by ryanplusplus** [comment]
What is the intent of this change?

**Comment by wolf99** [comment]
This seems a very spurious change at best.
(As such I would recommend that the PR be closed without merge if no response is forthcoming to Ryan's question within the next few days)

**Comment by wolf99** [comment]
Checking the requester's profile, the other only other actions are all PRS all from the same period, all making similar spurious commits. No idea why but I can't think of any good reasons.
Given this and the lack of response to earlier questions, I'm closing this.

**Comment by ryanplusplus** [comment]
Hacktoberfest

**Pull request closed without merging**
