### PR TITLE
Remove Broken URL

### PR DESCRIPTION
**Pull request by orsenthil**
Remove Broken URL

### CODE REVIEW

**Comment by ryanplusplus** [comment]
I think this comes from upstream. Can you apply the fix [here](https://github.com/exercism/problem-specifications/blob/main/exercises/etl/metadata.toml) instead?

**Comment by wolf99** [comment]
Correct URL might be http://tutorials.jumpstartlab.com/  ?

**Comment by orsenthil** [comment]
https://github.com/exercism/problem-specifications/pull/2014 

- Should we need fixes at both places?

**Comment by wolf99** [comment]
If you fix it there, it will eventually get sync-ed to this repository.

**Comment by wolf99** [comment]
This can be closed as the PR on the problem-specs repo will cover this.

**Pull request closed without merging**
