### PR TITLE
word-count: change to TEST_ASSERT_EQUAL_STRING_LEN() in tests

### PR DESCRIPTION
**Pull request by wolf99**
Per #357, have changed test to use `TEST_ASSERT_EQUAL_STRING_LEN` test assert instead of `TEST_ASSERT_EQUAL_UINT8_ARRAY`.

Change is still under discussion on the issue, so have marked as WIP for now.

### CODE REVIEW

**Comment by ryanplusplus** [comment]
Can we add a comment per https://github.com/exercism/c/issues/357#issuecomment-505603234 so that students have a hint as to how to pass this check?

Looks good otherwise :+1:

**Comment by wolf99** [comment]
Added to `word-count/.meta.hints.md` and re-generated the `README.md` for the exercise

**Comment by ryanplusplus** [comment]
:+1:

**Comment by wolf99** [comment]
closes #357

**Pull request merged**
