### PR TITLE
🤖 Update tests.toml files to latest spec

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Track maintainers found that they wanted to add comments to the tests.toml file to e.g. indicate _why_ a test was not included.
Unfortunately, running configlet sync would re-generate the entire file so any manually added comments were lost.

In this PR we're updating the format of tests.toml files to support adding comments.
We do this by creating a separate table for each test case which has `description` and `include` fields.
Tracks are then free to add additional fields, like a `comment` field, but also any other fields they feel might be useful to them.

configlet has _not_ yet been updated to support this new format, but we hope to do this soon. Sorry for the inconvenience.

For more information, see this discussion: https://github.com/exercism/configlet/issues/186

## Implementation

The PR expects the tests.toml files to be in their original format:

```toml
# <description>
"<uuid>" = <include>
```

This is transformed to:

```toml
[<uuid>]
description = "<description>"
include = <include>
```

## Example

```toml
# one factor has multiples within limit
"361e4e50-c89b-4f60-95ef-5bc5c595490a" = true
```

becomes

```toml
[361e4e50-c89b-4f60-95ef-5bc5c595490a]
description = "one factor has multiples within limit"
include = true
```

## Existing comments

As some tracks have manually added comments to tests, we try to detect them by assuming they are either:

- Added as a line comment _before_ the description (we'll ignore empty lines)
- Added as an inline comment _after_ boolean include value

For any such manually detected comments, we'll add a `comment` field.

## Tracking

https://github.com/exercism/v3-launch/issues/22

### CODE REVIEW

**Comment by wolf99** [comment]
Hi @ErikSchierboom is merging this dependent on the configlet update?

That is, if we merge this change right now and then run configlet will it complain that the `tests.toml` is the wrong format - or just overwrite it? Or maybe it's a chicken/egg situation and we should change this and then *not* run configlet on it until configlet is updated?

**Comment by wolf99** [comment]
Running configlet against the tests.toml in this branch shows that it does not recognise the tests when specified in this new format. 

Leaving this PR unmerged until the configlet catches up.

**Comment by ErikSchierboom** [comment]
> Running configlet against the tests.toml in this branch shows that it does not recognise the tests when specified in this new format. 

That is correct, sorry about that.

**Comment by wolf99** [comment]
NP @ErikSchierboom . Is there a PR or work ongoing to get configlet up on this? I'll try to help out if I can.

**Comment by ErikSchierboom** [comment]
@wolf99 There is no PR being worked on at the moment. The spec can be found here: https://github.com/exercism/configlet/issues/198 Help is much appreciated!

**Comment by ee7** [comment]
As of the [latest configlet release](https://github.com/exercism/configlet/releases/tag/4.0.0-alpha.14), `configlet sync` now supports the new `tests.toml` format.

Please let me know if you find any problems with it.

**Comment by wolf99** [comment]
Changes look good.
Have run newest configlet locally and this seems to result in the same output as earlier configlet versions with the existing tests.toml files.

**Review by wolf99 — APPROVED** [review]

**Comment by wolf99** [comment]
This missed linked-list again @ErikSchierboom 😔

**Pull request merged**
