### PR TITLE
Update README to describe the anatomy of the exercise directory structure

### LINKED ISSUE #103: Add an explanation of example.c/h to README
The main contributing guide explains a little about how example solutions work across the Exercism tracks, but the usage here of example.c, example.h, and the provided headers should be explicitly explained in our README.

The same patch would likely apply to the exercism/xcpp repo as well.

### PR DESCRIPTION
**Pull request by JamesAnthonyLow**
I set out to close #103 using @RealBarrettBrown's changes on #120 but I think a more complete description of the exercise directories was necessary to explain the ```example.{c|h}``` files so I created an *Exercise Anatomy* section.

### CODE REVIEW

**Comment by JamesAnthonyLow** [comment]
Not sure why this is a conflicting change.  I'm pretty new to contributing to open source so if anyone can explain this I'd really appreciate it.

**Comment by ryanplusplus** [comment]
@JamesAnthonyLow I'm not 100% sure why there was a conflict, but it could be that you forked from an older commit. I resolved the conflict and everything looks good. Thanks!

**Comment by JamesAnthonyLow** [comment]
Awesome thank you! This was my first contribution to open source ever!

**Comment by ryanplusplus** [comment]
That's awesome! Once you get comfortable with the tools and workflow it's remarkably easy. Good luck!

**Pull request merged**
