### PR TITLE
Beer Song approach

### PR DESCRIPTION
**Pull request by bobahop**
Approach for Beer Song

### CODE REVIEW

**Comment by bobahop** [comment]
@wolf99: C approach for Beer Song ready for review.

**Review by wolf99 — COMMENTED** [review]
Looks good!
One thing though, the code refers to the sets of words as `LINE`s, whereas the text refers to verses.
It may reduce confusion for the code to also use the verses term?

**Comment by bobahop** [comment]
@wolf99: Thanks!

The text refers to LINEs and verses, as there are two lines in each verse, as it states here

```
Arrays are defined to hold the varying values for the first and second lines of each verse. 
```

Do you have a suggestion on how to further clarify?

**Comment by wolf99** [comment]
Ah, I misunderstood.
Then all seems good to me, approved!

**Review by wolf99 — APPROVED** [review]

**Pull request merged**
