### PR TITLE
Add memcheck make target

### PR DESCRIPTION
**Pull request by wolf99**
Per #169 and #241

### CODE REVIEW

**Comment by wolf99** [comment]
Should be good to go now I think.

**Comment by ryanplusplus** [comment]
Can we update the Travis script to execute this now? This would be a strong check for whether this hits every exercise.

**Comment by wolf99** [comment]
Added to CI - seems to work fine (after fixing missing pesky quote mark!).
I have tested that it does produce a valid fail on my own machine by adding a `malloc(10)` call to the `example.c` for `hello-world` and running `$ ./bin/run-tests`. Would be great if someone could check that also to ensure I'm not missing something silly 😄

**Comment by ryanplusplus** [comment]
LGTM :+1:

**Comment by wolf99** [comment]
Closes #169

**Pull request merged**
